const questions = [
    { question: "En Excel, Google Sheets o GeoGebra, ¿qué símbolo OBLIGATORIO le indica al programa que estás a punto de escribir una fórmula matemática poderosa y no un simple texto decorativo?", options: ["El símbolo de suma (+)", "El signo de igual (=)", "El asterisco (*)", "Las comillas dobles (\")"], correct: 1 },
    { question: "¿Cuál es la principal y más grande ventaja operativa de usar referencias de celdas (como A1 o B2) en lugar de escribir los números directos a mano en una fórmula?", options: ["Que las letras son más fáciles de leer que los números", "Que hace que el documento pese menos bytes de memoria", "Que si un día cambias el número base en la celda original, absolutamente todos los cálculos que dependen de ella se actualizan automáticamente", "No hay ninguna ventaja real, es solo estilo visual"], correct: 2 },
    { question: "Si la celda A1 tiene el valor 8000 (el costo de un carro), ¿cuál es la fórmula más profesional y directa para calcular su precio total final sumándole el 16% de IVA en la celda B1?", options: ["=A1 + 16%", "=A1 * 1.16", "=A1 * 0.16 (eso solo daría el IVA aislado)", "=A1 / 16"], correct: 1 },
    { question: "Tienes el número 5 alojado en A1 y el número 10 alojado en A2. ¿Cuál es la fórmula correcta para representar la fracción 5/10 usando celdas?", options: ["=5/10", "A1 / A2 (Falta el signo igual)", "=A1/A2", "fraccion(A1,A2)"], correct: 2 },
    { question: "¿Qué sucede catastróficamente en una hoja de cálculo si tienes una fórmula perfecta (como =A1*0.50), pero accidentalmente alguien escribe la palabra 'Hola' en la celda A1?", options: ["Te dará el resultado 'HolaHola' duplicado", "El programa ignorará el texto y dará cero mágicamente", "Dará un mensaje de ERROR (como #¡VALOR!), porque es imposible multiplicar texto por un número", "Convertirá automáticamente la palabra a un código numérico"], correct: 2 },
    { question: "Si quieres calcular una fracción de otra fracción (ej. la mitad de tres cuartos). Tienes 3/4 escrito como número decimal (0.75) en la celda C1. ¿Cómo calculas ágilmente su mitad exacta en otra celda?", options: ["=C1 * 2", "=C1 / 2 (o lo que es lo mismo, =C1 * 0.5)", "=C1 - 0.5", "Esas operaciones no se pueden hacer con referencias de celdas"], correct: 1 },
    { question: "En el argot tecnológico, matemático y de la ciencia de datos, ¿qué significa exactamente crear un 'modelo' en una hoja de cálculo?", options: ["Hacer que la tabla se vea bonita, con colores pasteles y bordes", "Diseñar un sistema inteligente de fórmulas y celdas entrelazadas que responde lógicamente cuando introduces datos o escenarios nuevos", "Ponerle contraseñas de seguridad al archivo", "Usar números muy grandes para impresionar al jefe"], correct: 1 }
];
