const questions = [
    { question: "En el mundo rudo y real del álgebra superior, ¿qué se considera formal y técnicamente una 'Operación Combinada Compleja'?", options: ["Simplemente una suma que tiene muchos números", "Una ecuación masiva que mezcla agresivamente todos los elementos a la vez en una misma línea: sumas, restas, potencias, raíces, multiplicaciones, divisiones y signos de agrupación", "Una división que obligatoriamente da muchos decimales", "Una fracción impropia que no se puede reducir"], correct: 1 },
    { question: "Como un francotirador, evalúa el primer paso de esta bestia: 10 + (2³ - √25). Según la ley militar de PEMDAS, ¿dónde debes clavar tu mirada y atacar PRIMERO sin dudar?", options: ["Sumar relajadamente 10 + 2", "Mirar directamente adentro del paréntesis y atacar a los 'reyes' absolutos: resolver la potencia (2³) y la raíz (√25)", "Sacarle la raíz al número 10 de afuera", "Restar la raíz a la potencia sin siquiera haberlas resuelto"], correct: 1 },
    { question: "Termina con sangre fría el problema anterior: Una vez que ya resolviste exitosamente la potencia (2³ = 8) y la raíz (√25 = 5), el paréntesis te queda resumido como (8 - 5). Si resuelves esa simple resta (da 3), ¿cuál es el resultado FINAL e indiscutible de toda la ecuación resumida '10 + 3'?", options: ["13 exactos", "30", "7", "0 absoluto"], correct: 0 },
    { question: "¡Cuidado con la trampa visual en programación! En el programa GeoGebra o en Excel, si escribes la expresión con techo largo √(9 + 16) usando el comando 'sqrt(9 + 16)', ¿qué operación matemática se hace primero por obligación lógica computacional?", options: ["El procesador saca la raíz de 9 primero", "El procesador saca la raíz de 16", "La computadora PRIMERO hace la suma obligatoria que está encerrada adentro del bloque (9+16=25), y HASTA EL FINAL le saca la raíz a ese número 25 sumado, arrojando un 5 perfecto", "La máquina multiplica todo por cero y se apaga"], correct: 2 },
    { question: "¿Qué desgracia pasaría en tus cálculos si caes redondito en la trampa visual y decides escribir y resolver las raíces por separado así: 'sqrt(9) + sqrt(16)'?", options: ["Da mágicamente el mismo resultado correcto (5)", "Da un resultado totalmente distinto y erróneo: Primero sacarás las raíces individuales (3 y 4) y luego las sumarás falsamente, dando como resultado 7. (Arruinaste la ecuación)", "La calculadora se bloquea y da error", "Da un número infinito"], correct: 1 },
    { question: "Aplica tu dominio total de la jerarquía: Resuelve en la mente y sin errores ' (10 - 2) * 3² '", options: ["72 (Impecable: Primero salvas el paréntesis 10-2=8. Luego elevas al rey potencia 3²=9. Al mero final, la nobleza multiplica los resultados 8*9=72)", "144", "24", "18"], correct: 0 },
    { question: "El éxito rotundo al resolver operaciones combinadas complejas sin cometer jamás un error, en realidad no depende de ser un genio matemático que nació sabiendo, sino que depende EXCLUSIVAMENTE de...", options: ["Tener una calculadora japonesa muy cara", "Ser extremadamente rápido sumando mentalmente", "Tener disciplina de hierro militar, tener paciencia zen, y seguir el algoritmo PEMDAS paso a paso con frialdad, reescribiendo la ecuación limpia en el papel hacia abajo en cada paso", "Tener suerte y buena caligrafía"], correct: 2 }
];
