const questions = [
    { question: "En la arquitectura matemática del software de diseño, un 'Término Algebraico' es como un ladrillo indestructible. ¿Qué símbolos están ESTRICTAMENTE PROHIBIDOS dentro de un solo término y sirven más bien para separar un término de otro?", options: ["Los signos de multiplicación oculta y división", "Los signos de Suma ($+$) y Resta ($-$). ¡Un término corporativo jamás puede tener un $+$ o un $-$ metido a la mitad! Esos signos actúan como fronteras, muros o pegamento que separan un ladrillo de diseño de otro distinto", "Los paréntesis curvos", "Las letras minúsculas del abecedario"], correct: 1 },
    { question: "¿Cuáles son las 4 partes vitales, anatómicas y obligatorias que componen la estructura perfecta de un término algebraico como $-5x^2$?", options: ["Tinta negra, papel, regla y compás", "El Signo ($-$), el Coeficiente numérico ($5$), la Variable ($x$) y el Exponente poderoso ($2$). Si dominas y entiendes estas cuatro partes sin dudar, podrás programar cualquier máquina láser de la fábrica", "Raíz, tronco, ramas y hojas", "Suma, resta, multiplicación y división"], correct: 1 },
    { question: "En un taller de costos reales, el 'Coeficiente' es el número gigante que está enfrente de la letra (Ej. el $4$ en $4y$). ¿Qué maldita y crucial información te da este número?", options: ["Te dice el color de la madera y el barniz", "¡Te dice la CANTIDAD exacta! Te grita en la cara 'cuántas veces' tienes ese bloque de madera o ese costo. En $4y$, tienes $4$ piezas idénticas de medida $y$. Es el jefe numérico supremo de la operación", "Te dice que restes $4$ unidades al final", "Te dice la temperatura a la que debe estar el láser"], correct: 1 },
    { question: "Un ingeniero novato en la fábrica escribe simplemente la letra solitaria '$x$' en el software sin ningún número gigante al frente. ¿Qué coeficiente secreto e invisible está ahí aunque no se haya molestado en escribirlo?", options: ["Un Cero gigante para destruir todo ($0x$)", "¡El número Uno ($1$)! Escribir '$x$' es exacta y matemáticamente lo mismo que escribir '$1x$'. Tienes 'una sola' pieza de madera. El uno es tan obvio y evidente en la industria que por elegancia jamás perdemos tiempo en escribirlo", "El infinito cósmico", "El número Diez mágico"], correct: 1 },
    { question: "El 'Exponente' es el numerito flotante arriba de la letra. En el mundo del diseño y corte de materiales, ¿qué dimensión física representa el exponente '$2$' (Ej. $x^2$)?", options: ["Una simple línea delgada en el papel", "¡Un ÁREA bidimensional! (Como un cuadrado plano de madera cortado en la mesa). El exponente $2$ ($x$ multiplicado por $x$) siempre te habla de superficies planas. Si fuera $3$ ($x^3$) hablaríamos de Volumen 3D y cajas completas", "Un peso muerto en kilogramos", "El precio de venta final"], correct: 1 },
    { question: "Si juntas inteligentemente varios términos (ladrillos) y los unes con pegamento de sumas y restas, creas un muro gigante (Ej. $3x^2 - 5x + 8$). ¿Cómo se le llama oficialmente en la industria a este muro completo?", options: ["Un Enigma numérico indescifrable", "Una 'Expresión Algebraica'. Es el conjunto de varios términos unidos en una sola línea de código. Es la fórmula final que le entregarás a tu gerente para calcular el presupuesto total", "Un Término Infinito y mutante", "Una Ecuación Mágica de la suerte"], correct: 1 },
    { question: "Inspección de calidad corporativa: En la gran expresión de costos $Costos = 15x - 8y + 500$, ¿por qué al número aislado '$500$' se le llama formalmente 'Término Independiente'?", options: ["Porque fue escrito en color rojo para llamar la atención", "¡Porque no depende de ninguna maldita letra esclava! No tiene variable. Es un número fijo y rebelde. En la industria, representa los costos fijos que nunca cambian en el mes (como la renta del local o la luz), sin importar cuántas piezas ($x$) o ($y$) decidas fabricar", "Porque siempre va al inicio de la oración", "Porque es un número muy grande y gordo"], correct: 1 }
];
