const questions = [
    { question: "¿Qué característica matemática define estrictamente a una fracción impropia (como 11/8)?", options: ["El denominador es más grande que el numerador", "El numerador (arriba) es mayor o igual al denominador, por lo que vale un entero completo o más", "Son fracciones que dan números negativos", "Siempre tienen un número entero al lado izquierdo"], correct: 1 },
    { question: "Si pides 11/8 de pizza en una fiesta, visualmente esto significa en cajas reales que vas a recibir:", options: ["11 pizzas completas", "Menos de una pizza", "1 pizza entera y 3 rebanadas extra de la segunda pizza (1 3/8)", "8 pizzas enteras y 3 rebanadas extra"], correct: 2 },
    { question: "¿Cuál es la conversión correcta y exacta de la fracción impropia 7/5 a fracción mixta (enteros y sobrante)?", options: ["2 enteros y 1/5", "1 entero y 2/5", "7 enteros y 5", "No se puede convertir sin calculadora"], correct: 1 },
    { question: "En un proyecto eléctrico necesitas 15/4 metros de alambre. ¿Cuántos rollos enteros de 1 metro debes comprar como mínimo en la ferretería para que no te falte material?", options: ["3 rollos", "4 rollos (porque 15/4 metros son 3.75 metros, si compras 3 te faltará)", "15 rollos", "No necesitas alambre"], correct: 1 },
    { question: "Visualmente, ¿cuántos enteros COMPLETOS hay escondidos dentro de la enorme fracción impropia 20/6?", options: ["2 enteros", "3 enteros (porque 6 * 3 = 18, sobran 2)", "4 enteros", "20 enteros"], correct: 1 },
    { question: "Si usas GeoGebra CAS y divides 11/8, el resultado decimal es 1.375. ¿Qué nos indica el número '1' que está a la izquierda del punto decimal?", options: ["Un error de cálculo de la computadora", "Los enteros completos que conforman la fracción impropia", "El sobrante inútil", "Los milímetros de la regla"], correct: 1 },
    { question: "¿Por qué las matemáticas inventaron las fracciones impropias si podemos usar fracciones mixtas en la vida real?", options: ["Para confundir a los alumnos en los exámenes", "Porque las fracciones impropias son más puras y fáciles de usar para multiplicar o dividir en álgebra avanzada", "Porque ocupan menos tinta al escribirlas", "Porque las fracciones mixtas son ilegales en la ciencia moderna"], correct: 1 }
];
