[build]
  publish = "."

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Access-Control-Allow-Origin = "*"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false
  # Nota: El redirect a index.html es util para Single Page Apps (SPA)
  # Pero como estamos usando multiples HTML (PVS01.HTML), si navegan directo funcionará
  # Si buscas un HTML inexistente, caerá al index.html
