const questions = [
    { question: "¿Qué significa exactamente el concepto profesional y corporativo de 'Revisión por Pares' (Peer Review) en el desarrollo de un proyecto analítico?", options: ["Que el profesor jefe hace absolutamente todo el trabajo pesado", "Que debes evaluar y auditar críticamente y sin sesgos el modelo matemático de un colega o compañero, de la misma estricta forma que él evalúa el tuyo", "Que se revisa obligatoriamente trabajando en la misma computadora física", "Que el trabajo se publica rápidamente en internet sin revisar nada"], correct: 1 },
    { question: "Auditoría 1: Tu compañero escribió en su bitácora que el terreno total de la colonia es de 50 hectáreas, y el área verde pura son 10 hectáreas. Luego construyó su fracción modelo como 50/10. ¿Cuál es tu veredicto inmediato de auditor?", options: ["Está matemáticamente perfecto", "Error conceptual grave: Colocó el total (50) arriba en el numerador, cuando el total de referencia SIEMPRE debe ir como cimiento abajo, en el denominador (10/50)", "Le faltó el punto decimal en la escritura", "Está mal porque no usó el cálculo del MCM"], correct: 1 },
    { question: "Auditoría 2: Alguien de tu equipo afirma ruidosamente que la fracción 20/100, simplificada a su mínima expresión elegante, es 2/10. Como auditor, ¿esto es matemáticamente definitivo y correcto?", options: ["No, tiene un error de procedimiento, porque la mínima expresión irreducible real y final es 1/5", "Sí, es impecable y correcto", "Es falso porque la división y respuesta final es cero", "Sí, la computadora dictamina que no se puede simplificar más"], correct: 0 },
    { question: "Auditoría 3: Un equipo ajeno calculó en el pizarrón que su parque ocupa la enorme fracción 1/2 del terreno urbano. En su reporte oficial ante la alcaldía afirman audazmente que esto representa un pobre 5% de áreas verdes protegidas. ¿Cuál es tu corrección de auditor?", options: ["Es correcto, 1/2 es matemáticamente el 5%", "Error garrafal de punto decimal: la fracción 1/2 representa la mitad absoluta del todo, es decir, el 50% gigante, no el mísero 5%", "La fracción 1/2 representa en realidad el 100% total", "El concepto de porcentaje no existe en el urbanismo"], correct: 1 },
    { question: "Si auditas un documento de Excel de finanzas corporativas y ves la fórmula central '=A1 * 0.20' para calcular automáticamente un impuesto al cliente. ¿Qué porcentaje exacto está calculando y cobrando esa fórmula matemática?", options: ["El 2%", "El 0.2%", "El 20% neto", "El 200% exagerado"], correct: 2 },
    { question: "Si vas a auditar y verificar rápidamente si la fracción urbana 14/28 equivale exactamente al 50% de desarrollo, usando el CAS de GeoGebra, ¿cuál es la sintaxis de programación lógica y perfecta que debes teclear?", options: ["14+28 = 50", "14/28 == 50% (El doble signo igual le ordena al software comprobar estrictamente equivalencias de valores)", "50% * 14/28", "CAS(14,28)"], correct: 1 },
    { question: "¿Por qué un error humano en la asignación del denominador inicial arruina irremediablemente todo un modelo matemático posterior?", options: ["Porque el denominador define la base entera del 'universo' de referencia. Si la base está construida mal, todos los porcentajes, gráficas y simplificaciones posteriores que se le presenten al cliente serán una mentira amplificada", "No importa realmente, el software y el resultado se corrigen solos al final", "Solo afecta estéticamente el color de la gráfica en Excel", "Porque las leyes de las matemáticas son siempre crueles"], correct: 0 }
];
