const questions = [
    { question: "¿Cuál es la característica principal, absoluta y sagrada de un 'Monomio', el lobo solitario del álgebra industrial?", options: ["Que siempre tiene muchos colores brillantes en los libros de texto", "Es una expresión algebraica corporativa de UN SOLO término indestructible (como $5x^2$). Es un bloque macizo que no tiene ningún signo de Suma ($+$) o Resta ($-$) que lo parta a la mitad o lo debilite", "Que siempre es un número negativo, malo y destructivo para las finanzas", "Que solo tiene letras minúsculas y jamás tiene números gigantes (coeficientes)"], correct: 1 },
    { question: "En el diseño avanzado de piezas de madera láser, si un monomio tiene un exponente '$2$' (al cuadrado) o está formado por dos letras distintas unidas ($xy$), ¿qué tipo de dimensión física real está modelando para la máquina?", options: ["Una simple línea recta infinita y aburrida (1D)", "¡Un ÁREA plana bidimensional (2D)! Al multiplicar base por altura siempre generas superficies planas (metros cuadrados). Por ejemplo, $x \\cdot x = x^2$ o $x \\cdot y = xy$. Esta matemática es vital y obligatoria para calcular exactamente cuánta hoja de MDF vas a gastar", "El peso muerto de la madera hundiéndose en el agua", "El volumen de una caja de cartón tridimensional (3D)"], correct: 1 },
    { question: "Si tu cliente corporativo te pide fabricar un rectángulo de MDF donde la base mide '$4x$' y la altura mide '$2x$'. Al aplicar la fórmula universal de $Área = Base \\cdot Altura$, ¿cuál es el Monomio final resultante que le programarás a la máquina láser?", options: ["$6x$ (Porque solo sumaste como novato de primaria)", "¡$8x^2$! Multiplicas despiadadamente los números corporativos con los números ($4 \\cdot 2 = 8$) y multiplicas ferozmente las variables con las variables ($x \\cdot x = x^2$). Este monomio letal calculará el área perfecta siempre", "$8x$ (Olvidaste multiplicar las letras y arruinaste la fórmula)", "$2x^2$ (Hiciste una resta absurda que quebrará la empresa)"], correct: 1 },
    { question: "En el estricto departamento de control de calidad, el jefe te pide averiguar el 'Grado Absoluto' del monomio gigante $7x^2y^3$. ¿Cómo calculas mentalmente este rango corporativo en un segundo?", options: ["Mirando únicamente el coeficiente numérico mayor (7)", "¡Sumando velozmente todos los exponentes de sus letras esclavas! En este caso sumas el exponente $2$ (de la letra $x$) más el exponente $3$ (de la letra $y$). $2 + 3 = 5$. Le dices al jefe con voz firme: 'Es un monomio de grado 5 o Rango 5, señor'", "Restando las variables con calculadoras", "Multiplicando todos los números a lo loco a ver qué sale"], correct: 1 },
    { question: "El gerente general te pone a prueba bajo presión con una pieza especial: La base del mueble mide '$5a$' y la altura mide '$3b$'. ¿Cuál es el monomio perfecto que representa el área total a cotizar?", options: ["$8ab$ (Sumaste mal bajo presión)", "¡$15ab$! Los números gigantes ($5 \\cdot 3$) te dan $15$. Las letras distintas ($a \\cdot b$) no se pueden mezclar en cuadrados, así que simplemente se quedan pegadas formando la alianza indestructible '$ab$'. El láser entenderá al instante que debe multiplicar ambas medidas", "$15a^2$ (Inventaste cuadrados que no existen)", "$2a$ (Fallaste y te despidieron)"], correct: 1 },
    { question: "Si observas en el plano el monomio letal $-10xyz$, y el supervisor te pregunta de qué 'grado' es. ¿Qué debes recordar siempre sobre las letras que 'aparentemente' no tienen ningún exponente arriba?", options: ["Que el exponente es un cero absoluto y desaparecen del plano", "¡Que tienen un exponente invisible e implacable de $1$! La $x$ tiene $1$, la $y$ tiene $1$ y la $z$ tiene $1$. Si los sumas todos juntos ($1+1+1=3$), gritarás que el monomio es de grado 3 (lo cual probablemente represente un volumen físico 3D muy costoso)", "Que son errores de tipeo del teclado del diseñador novato", "Que son variables negativas y destruyen el valor del mueble"], correct: 1 },
    { question: "Conclusión de Presupuestos ABP: ¿Por qué diablos es tan poderoso, importante y gerencial modelar el área de las piezas del cliente usando monomios (como $6x^2$) en lugar de usar simples números fijos de primaria?", options: ["Porque a los contadores estirados les gustan los nombres raros como 'monomios'", "¡Por la majestuosa automatización! Si escribes el monomio inteligente $6x^2$ en tu Excel de cotización, no importa si el indeciso cliente cambia de idea 100 veces sobre el tamaño final de la $x$. El área total y el costo del material se actualizarán solos y sin el más mínimo esfuerzo al instante", "Para cobrar mucho más caro el diseño en el mercado negro", "Para confundir a los albañiles que arman el mueble en la fábrica"], correct: 1 }
];
