const questions = [
    { question: "¿Cuál es el 'mito falso' más extendido y peligroso en las escuelas sobre los exponentes negativos (ejemplo: 5^-2)?", options: ["Creer ingenuamente que la base se debe sumar", "Creer y asegurar ilusamente que el resultado final será un número negativo", "Pensar que estos números no existen en la vida real", "Pensar que se resuelven obligatoriamente con fracciones"], correct: 1 },
    { question: "En matemáticas avanzadas, ¿qué instrucción real y puramente técnica te está dando el signo 'menos' escondido en un exponente?", options: ["Le ordena a la base multiplicarse por menos uno", "Le indica sumar un número negativo a la ecuación", "Te ordena convertir la base material en su INVERSO MULTIPLICATIVO (es decir, volverla una fracción poniendo un 1 arriba de ella)", "Le indica restar la base del todo"], correct: 2 },
    { question: "Aplica la Regla del Ascensor en tu mente: ¿Cómo se reescribe correctamente la potencia 4^-3 para poder calcularla de forma positiva?", options: ["1 / 4^3 (Mandando la base al denominador)", "4 / 3", "-12", "-4^3"], correct: 0 },
    { question: "Usando tu recién adquirido conocimiento de cálculo, ¿cuál es el resultado final exacto y fraccionario de resolver 2^-3?", options: ["-8 (Totalmente falso)", "1/8 (Porque lógicamente es 1 dividido entre 2 al cubo positivo)", "-6", "1/6"], correct: 1 },
    { question: "¿Para qué propósito fundamental se usan en la vida real los exponentes negativos de base 10 (como por ejemplo 10^-9) en ciencias duras como la física cuántica o biología molecular?", options: ["Para calcular las distancias astronómicas entre galaxias lejanas", "Para poder medir, expresar y leer dimensiones de cosas a nivel microscópico o subatómico (como átomos, virus y células) sin tener que escribir aburridas filas de millones de ceros decimales en el papel", "Para medir el peso gravitacional de los planetas", "Para confundir visualmente a los estudiantes de secundaria sin motivo"], correct: 1 },
    { question: "Si usas el poder algorítmico del CAS de GeoGebra y tecleas la instrucción '10^-2', ¿qué fracción irreducible, elegante y exacta te arrojará el sistema computacional?", options: ["1/10", "1/100 (Equivalente a un centésimo de entero)", "-100", "0.01/10"], correct: 1 },
    { question: "Completa de forma impecable la frase técnica de esta sesión: 'Un exponente negativo nunca jamás hace negativo al resultado numérico, simplemente hace que la magnitud sea muy...'", options: ["Grande", "Rara y compleja", "Pequeña, diminuta (Es decir, muy cercana al cero, pero siempre del lado positivo)", "Oscura y abstracta"], correct: 2 }
];
