const questions = [
    { question: "En el taller de diseño corporativo, ¿qué regla física y vital debes respetar religiosamente al usar el 'Ensamblaje Vertical' para sumar dos muebles pesados (polinomios)?", options: ["Alinear todos los números de menor a mayor para que se vea estético", "¡Alinear obligatoria y milimétricamente los Términos Semejantes en las mismas columnas! Tienes que poner las 'equis' exactamente debajo de las 'equis', y las 'yes' debajo de las 'yes'. Si acomodas mal una sola pieza bajo otra de distinta familia, el cálculo explotará y el mueble saldrá completamente chueco", "Alinear todo a la derecha como si estuvieras escribiendo un poema en Word", "Ignorar las letras, borrarlas y sumar solo la primera columna numérica"], correct: 1 },
    { question: "El jefe de taller te exige sumar $Módulo A: (4x + 7y)$ con el $Módulo B: (2x - 3y)$. Usando tu mente fría y la alineación de columnas, ¿cuál es el mega-mueble resultante?", options: ["$6x - 10y$ (Restaste mal la segunda columna y echaste a perder el material)", "¡$6x + 4y$! Columna de las $x$: $4+2=6$. Columna de las $y$: $7-3=+4$. El ensamble es estructuralmente perfecto y sin el más mínimo fallo", "$8xy$ (Multiplicaste a lo loco, destruiste la forma geométrica y te despidieron)", "$6x - 4y$ (Grave error de signo negativo)"], correct: 1 },
    { question: "¡Alerta Roja en el almacén central! El cliente ordenó una RESTA de muebles para reducir costos: $Mueble A - Mueble B$. ¿Qué daño o alteración le causa el signo de Resta ($-$) al polinomio de abajo antes de poder ensamblarlo?", options: ["Lo borra de la memoria de la computadora", "¡Le cambia agresivamente el signo a TODOS y cada uno de los términos del polinomio de abajo! Es un virus letal en el software. Los términos positivos se vuelven negativos y los negativos se vuelven positivos. Después de ese cambio obligatorio, ya puedes sumar las columnas normalmente", "Solo le cambia el signo al primer número por respeto a los demás", "No le hace absolutamente nada, es inofensivo"], correct: 1 },
    { question: "Evalúa tu capacidad de Resta Industrial bajo presión: Tienes $(8x - 5) - (3x + 2)$. Aplica la regla del virus negativo y encuentra el presupuesto de reducción final.", options: ["$5x - 3$ (No le cambiaste el signo al $+2$, el cliente te demandará)", "¡$5x - 7$! El virus negativo ataca sin piedad al segundo paréntesis: El número $3x$ se vuelve $-3x$, y el $+2$ se vuelve $-2$. Ahora sumas tranquilamente las columnas: $(8 - 3 = 5x)$ y $(-5 - 2 = -7)$. Ensamble perfecto", "$11x - 3$ (Lo sumaste en lugar de restarlo, el cliente pagó de más)", "$5x + 3$ (Errores aleatorios sin sentido)"], correct: 1 },
    { question: "Vas a alinear verticalmente en la pantalla de la cortadora láser: $A = 5x^2 + 3x$ y $B = 4x + 2$. ¿Qué haces si al polinomio de arriba le falta la columna de los 'números sueltos' para alinearse con el humilde $2$ del polinomio de abajo?", options: ["Pones el $2$ a la fuerza debajo del $3x$ y los sumas cruzados", "¡Dejas un respetuoso espacio en blanco (o un cero fantasma) en esa columna superior! NUNCA debes forzar piezas de distintas familias a encajar. El número $2$ simplemente bajará intacto al resultado final de la factura", "Borras el $2$ del plano porque sobra y estorba", "Sumas el $2$ a los exponentes cuadrados"], correct: 1 },
    { question: "Calcula velozmente el costo del ensamble corporativo: Suma $(10x^2 - 4x) + (-3x^2 + 4x)$. ¿Qué ocurre mágicamente en la columna de las variables ligeras '$x$'?", options: ["Queda un ruidoso $8x$ en el plano", "¡Se anulan y se destruyen mutuamente! Tienes una deuda de $-4$ y le sumas un pago de $+4$, el resultado es cero absoluto. La columna de las $x$ desaparece por completo de la realidad. El resultado final, limpio y corporativo de todo el polinomio es solo $7x^2$", "Queda una deuda de $-8x$", "La máquina láser marca 'Error fatal 404'"], correct: 1 },
    { question: "Conclusión de Ensamblaje ABP y Negocios: ¿Por qué dominar a la perfección la suma y resta de polinomios te convertirá en el gerente más valioso de la empresa?", options: ["Para poder llenar más hojas de papel aburridas en el reporte mensual", "¡Porque la vida real industrial es modular! Los clientes no compran piezas sueltas, compran muebles enteros compuestos por módulos separados. Si sabes sumar los costos polinomiales del Módulo A con el Módulo B de forma rápida y sin mortales errores de alineación, podrás cotizar cocinas gigantes y ganar licitaciones en minutos", "Para presumir en redes sociales que sabes hacer rayas verticales derechas", "Para confundir y estafar a los competidores más pequeños del mercado"], correct: 1 }
];
