const questions = [
    { question: "En un proyecto de diseño real corporativo, el cliente exige usar tres materiales distintos: MDF ($x$), Cristal Templado ($y$) y soportes de Acero ($z$). ¿Qué regla de oro debes aplicar implacablemente al momento de reducir (sumar) el presupuesto total bruto?", options: ["Sumar todos los números juntos a lo loco y ponerles la letra $xyz$ al final para ahorrar tinta", "¡La inviolable Ley de Separación de Familias! Las 'equis' solo se operan con las 'equis', las 'yes' con las 'yes', y así sucesivamente. ¡Jamás, bajo ninguna circunstancia, puedes cruzar o sumar los coeficientes de letras distintas!", "Borrar las letras que sean muy caras como el Acero ($z$) para engañar al cliente", "Multiplicar todo cruzado para confundir intencionalmente al supervisor"], correct: 1 },
    { question: "Un empleado novato intenta fusionar $8x + 3y$ y te presenta orgulloso el resultado '$11xy$'. ¿Qué castigo corporativo merece por esto?", options: ["Un premio por haber ahorrado letras en el reporte", "¡El despido inmediato por negligencia! Cometió el pecado capital del álgebra industrial. Sumó coeficientes de familias distintas y, para colmo de males, pegó las letras creando un 'área' ($xy$) que ni siquiera existía en el diseño original. El resultado correcto era simplemente dejarlo intacto como estaba: $8x + 3y$", "Un aumento de sueldo por proactivo", "Un descanso de una hora en la cafetería"], correct: 1 },
    { question: "Tienes el siguiente caos contable en el almacén: $15x - 7x + 20y$. ¿Cuál es la forma correcta y profesional de reducir esto para el reporte del gerente general?", options: ["Sumar todo y poner arrogantemente $28xy$", "Operar fría y calculadoramente a la familia de la madera ($15x - 7x = 8x$). Como el Cristal ($20y$) está solo y no tiene con quién operarse, simplemente se pasa directo y se salva. El presupuesto corporativo final limpio y perfecto es: $8x + 20y$", "$8x - 20y$ (Le cambiaste el signo al cristal por un error de novato)", "$15x + 13y$ (Sumaste y restaste al azar)"], correct: 1 },
    { question: "Al escribir el resultado final de una reducción con varias letras involucradas, ¿qué estándar visual utilizan los ingenieros y softwares de diseño a nivel mundial para acomodar las piezas en la línea final?", options: ["Las acomodan por el número más grande primero para presumir", "¡Por estricto orden alfabético de la parte literal! Siempre va primero la $a$, luego la $b$, o en su defecto primero la $x$, luego la $y$ y al final la $z$. Esto evita mortales errores de lectura y hace que el presupuesto luzca impecable y 100% profesional ante el cliente", "Las acomodan como vayan cayendo en la hoja de papel", "Las acomodan por el orden de los colores de la madera"], correct: 1 },
    { question: "Prueba de alta presión gerencial: Reduce rápido el siguiente monstruo de costos fijos y variables antes de la junta: $10x + 5 - 4x - 2$. (Ojo de águila con los números sin letra)", options: ["$11x$ (Sumaste todo a lo loco y quebraste la empresa)", "¡$6x + 3$! Primero operas a la familia variable ($10x - 4x = 6x$). Después, atacas a la familia de los Términos Independientes o costos fijos ($5 - 2 = +3$). Juntas los dos resultados limpios sin mezclarlos y obtienes el diseño financiero perfecto", "$6x - 3$ (Te equivocaste horriblemente en la resta de los independientes)", "$9x$ (Te inventaste un número de la nada)"], correct: 1 },
    { question: "El láser reporta un error grave con la línea: $4y^2 - 3y + y^2 + 8y$. ¿Cómo unificas y reparas esto sin provocar un incendio en la fábrica?", options: ["Sumo todo y me da un glorioso $10y^3$", "¡Detectas inmediatamente a los gemelos exactos! Los cuadrados de área ($y^2$) van estrictamente con los cuadrados: $4y^2 + 1y^2 = 5y^2$. Las líneas normales ($y$) van con las líneas: $-3y + 8y = +5y$. El polinomio final reparado y ensamblado es: $5y^2 + 5y$", "$5y^2 - 5y$ (Fatal error de signo)", "$10y$ (Ignoraste los valiosos cuadrados por completo)"], correct: 1 },
    { question: "Conclusión de Arquitectura de Datos: ¿Por qué NUNCA se pueden reducir (sumar o restar) un término tipo $x$ con un término tipo $y$ en la vida real?", options: ["Porque el teclado de la computadora no lo permite", "Porque modelan cosas físicas completamente diferentes en la realidad del cliente. Sería como sumar estúpidamente 5 kilos de cemento sólido con 3 litros de agua y decirle al cliente que tienes '8 kilos de cemento-agua'. Es absurdo, ilegal y antinatural en las matemáticas financieras y de diseño", "Porque las reglas del gobierno local lo prohíben por ley", "Simplemente para hacerle la vida miserable a los estudiantes de prepa"], correct: 1 }
];
