const questions = [
    { question: "En la expresión matemática 5^3 (cinco a la tercera potencia o cinco al cubo), ¿quién es oficialmente la 'base' y quién es el 'exponente'?", options: ["5 es el exponente y 3 es la base", "Ambos números funcionan como bases", "5 es la base (el número que se multiplicará) y 3 es el exponente (el jefe que dice las veces que se repetirá)", "El 15 es la base final"], correct: 2 },
    { question: "¿Cuál es el 'error mortal' y más trágico que cometen todos los principiantes al intentar resolver la potencia 5^3 en un examen?", options: ["Multiplicar el 5 x 3 y decir ingenuamente que la respuesta es 15", "Sumar 5 + 3", "Dividir 5 entre 3 con calculadora", "Multiplicar rigurosamente 5 x 5 x 5"], correct: 0 },
    { question: "Calcula correctamente en tu mente la potencia 2^4 (el número dos elevado a la cuarta potencia):", options: ["8 (Grave error)", "16 (Resultado de multiplicar 2 x 2 x 2 x 2)", "6", "10"], correct: 1 },
    { question: "¿Cuál es el propósito matemático principal e histórico por el que los científicos inventaron la potenciación?", options: ["Para reprobar masivamente a los alumnos en álgebra", "Para no tener que sumar el mismo número muchas veces", "Para representar de forma corta, elegante y eficiente multiplicaciones repetidas del mismo número (ej. escribir 7^4 en lugar del largo 7 x 7 x 7 x 7)", "Para calcular divisiones inexactas"], correct: 2 },
    { question: "Si un peligroso virus informático se duplica cada hora que pasa. En la hora cero hay 1 virus. En la primera hora hay 2. A la segunda hora hay 4. Esto se representa algebraicamente como 2^H. ¿Cuántos virus habrá a la hora 5 (es decir, 2^5)?", options: ["Apenas 10 virus (Error mortal)", "32 virus informáticos (2x2x2x2x2)", "25 virus", "16 virus"], correct: 1 },
    { question: "En el desarrollo de software matemático avanzado (como GeoGebra) o en herramientas de oficina (como Excel), ¿cuál es el símbolo universal en el teclado de la computadora para indicarle a la máquina que calcule una potencia?", options: ["El signo más (+)", "El asterisco (*)", "La letra equis (X)", "El acento circunflejo o 'sombrerito' (^)"], correct: 3 },
    { question: "¿Cuánto vale numéricamente la potencia matemática 10^3 (diez al cubo)?", options: ["30", "100", "1000 (porque 10x10x10 = 1000, un uno seguido de tres ceros)", "10000"], correct: 2 }
];
