const questions = [
    { question: "¿Cómo puedes convertir inmediatamente y sin esfuerzo matemático cualquier número entero a una fracción válida?", options: ["Sumándole cero", "Poniéndole un uno (1) como denominador (ej. 8 se vuelve 8/1)", "Poniéndole un cero (0) como denominador", "Multiplicándolo por dos"], correct: 1 },
    { question: "Si divides un número entero entre 1 (por ejemplo, 15 / 1), ¿cuál es el resultado de la fracción?", options: ["Se hace fracción decimal", "Da cero por anulación", "El número permanece exactamente igual (15)", "Se vuelve negativo automáticamente"], correct: 2 },
    { question: "En un taller de ebanistería tienes 4 metros completos de madera. Si decides cortarlos visualmente en mitades (medios), ¿cuántas mitades obtendrás en total? (Pista: convierte 4/1 a medios amplificando)", options: ["2 mitades", "4 mitades", "8 mitades (es decir, 8/2)", "6 mitades"], correct: 2 },
    { question: "¿Cómo se les llama en matemáticas a las fracciones como 20/4 o 18/6 que, al momento de dividirlas, resulta que son números enteros perfectos disfrazados?", options: ["Fracciones Nulas", "Fracciones Decimales", "Fracciones Aparentes o Enteras", "Fracciones Complejas"], correct: 2 },
    { question: "Si usamos el software GeoGebra y escribimos la ecuación lógica ' 10 == 30/3 ', ¿qué responderá el simulador?", options: ["true (verdadero, son 100% equivalentes)", "false (falso)", "Dará un Error de sintaxis", "Responderá 10"], correct: 0 },
    { question: "En álgebra necesitas multiplicar el número 7 entero por la fracción 2/5. ¿Cuál es el primer paso correcto para hacerlo fácil y sin equivocarte?", options: ["Sumar 7 + 2 de frente", "Convertir el 7 a fracción poniéndole un 1 abajo (7/1)", "Eliminar la fracción del problema", "Convertir la fracción a un formato decimal"], correct: 1 },
    { question: "¿Cuál de las siguientes es indiscutiblemente una 'fracción aparente' que representa exactamente el número entero 3?", options: ["3/4", "9/3", "3/10", "1/3"], correct: 1 }
];
