const questions = [
    { question: "¿Cuál es el error mental, instintivo y más común que hace que la gente repruebe masivamente ejercicios de operaciones combinadas trampa, como (5 + 3 x 2)?", options: ["No saber sumar dos números de un dígito", "Leer y querer resolver el problema aritmético desesperadamente de izquierda a derecha, como si fuera un aburrido libro de texto normal", "Usar calculadora solar", "Sumar imprudentemente números negativos"], correct: 1 },
    { question: "En el mundo estricto e inflexible de las matemáticas, ¿qué dictamina o controla con mano de hierro la 'Jerarquía de Operaciones' (conocida como el protocolo PEMDAS)?", options: ["El orden innegociable de vida o muerte, o la autoridad exacta, en la que se DEBE resolver obligatoriamente cada operación particular dentro de una ecuación extensa", "El tamaño estético de los números impresos en la hoja", "El color de la gráfica proyectada en la pantalla", "Absolutamente nada, es una simple sugerencia amistosa para los alumnos"], correct: 0 },
    { question: "Evalúa tu disciplina. Resuelve esto puramente en tu mente usando la regla férrea PEMDAS: 10 + 4 * 2.", options: ["28 (Falso, caíste en la trampa de leer de izquierda a derecha: 10+4=14, y 14x2=28)", "18 (Correcto: porque la multiplicación manda. Primero multiplicas 4x2=8, y luego sumas 10+8=18)", "0", "16 cerrado"], correct: 1 },
    { question: "Según la rigurosa jerarquía militar de PEMDAS, ¿quiénes son los 'reyes' absolutos y tienen mayor autoridad prioritaria que las multiplicaciones o las aburridas divisiones?", options: ["Las sumas encadenadas", "Las restas largas", "Los poderosos Exponentes y las Raíces cuadradas", "Los números impares"], correct: 2 },
    { question: "Ponte a prueba: Si tienes una Multiplicación y una División pegadas y peleando en el mismo problema (ej. 10 / 2 * 5). Ambas tienen el MISMO nivel exacto de autoridad en el rango de PEMDAS. ¿Cuál resuelves primero para no crear una paradoja?", options: ["Siempre la multiplicación, por costumbre milenaria", "Siempre la división, por ser más difícil", "Ninguna de las opciones anteriores, me rindo", "Se resuelven estrictamente, de forma democrática, de izquierda a derecha según vayan apareciendo PRIMERO en el papel (En este caso específico, primero cae el 10/2=5, y luego multiplicas 5*5=25)"], correct: 3 },
    { question: "¿Cuál es el 'comodín', la carta oculta o la tarjeta de máxima prioridad absoluta en todas las matemáticas para obligar agresivamente a una máquina a romper el orden natural y forzarla a hacer una humilde suma ANTES que una potencia gigante?", options: ["Escribirlo más grande y con tinta roja", "Usar el amenazante símbolo de dinero en la ecuación", "Encerrar la humilde suma dentro de los sagrados Paréntesis ( )", "Multiplicar todo arteramente por cero"], correct: 2 },
    { question: "Demuestra de qué estás hecho: Resuelve en la mente y sin lápiz la operación ' 3^2 + 2 * 4 ' siguiendo a la letra la Jerarquía.", options: ["20 cerrado", "17 absoluto (Paso 1, el Rey Potencia: 3^2=9. Paso 2, la Reina Multiplicación: 2*4=8. Paso final, los peones de la Suma: 9+8=17)", "44 masivo", "100 irreal"], correct: 1 }
];
