const questions = [
    { question: "En la fábrica de álgebra, para clasificar el nivel de complejidad de un proyecto corporativo, debes contar rigurosamente cuántos 'ladrillos' (términos) tiene la fórmula. ¿Qué símbolos específicos debes buscar con tus ojos de águila porque actúan como los únicos 'muros separadores' reales entre un término y otro?", options: ["Los confusos signos de multiplicación ($*$) y división ($/$)", "Los signos de Suma ($+$) y Resta ($-$). ¡Son los únicos símbolos con el poder de separar un término de otro! Si cuentas visualmente cuántos $+$ y $-$ están libres en la expresión, sabrás exactamente cuántos bloques distintos de madera conforman el proyecto final", "Los paréntesis curvos y las comas", "Las letras mayúsculas del cliente"], correct: 1 },
    { question: "El gerente te entrega un presupuesto impreso que dice: $Costos = -15x^4y^2$. A simple vista parece un monstruo enorme, pero ¿cómo lo clasificas realmente para cobrarlo?", options: ["Es un inmenso Polinomio porque tiene muchos números, letras y exponentes pegados", "¡Es un simple y humilde Monomio! A pesar de verse intimidante y agresivo, NO HAY NINGÚN signo de Suma ($+$) o Resta ($-$) separando las letras. Todo está totalmente fusionado (multiplicado) en un solo y masivo bloque indestructible de madera", "Es un Binomio disfrazado para engañarte", "Es un Trinomio porque logras ver un $15$, una $x$ y una $y$ en el papel"], correct: 1 },
    { question: "Un cliente te pide un ensamblaje de MDF compuesto por la siguiente fórmula destructiva: $Área = 3x^2 - 12$. ¿Cuál es la clasificación oficial e industrial de este proyecto?", options: ["Un triste Monomio", "¡Un Binomio! Puedes ver claramente el signo rojo de Resta ($-$) funcionando perfectamente como un muro separador. Tienes un ladrillo pesado ($3x^2$) de un lado, y otro ladrillo ligero ($-12$) del otro. Son exactamente y sin lugar a dudas dos términos separados", "Un Trinomio de alta gama", "Una Ecuación infinita sin solución"], correct: 1 },
    { question: "¿Cómo se le llama oficialmente a una expresión de diseño corporativo que tiene exactamente TRES términos perfectamente separados, como el famoso $x^2 + 5x - 6$?", options: ["Triángulo Algebraico Isósceles", "Un Trinomio. Es el rey indiscutible de las ecuaciones cuadráticas y representa proyectos complejos que siempre están estructurados en tres fases financieras", "Binomio triple cuántico", "Un Monomio de tres cabezas"], correct: 1 },
    { question: "La palabra técnica 'Polinomio' viene del griego antiguo ('Poli' = muchos, 'Nomio' = términos). En la industria pesada del diseño, ¿a qué raras expresiones matemáticas les llamamos comúnmente Polinomios?", options: ["Solo a las fórmulas que tienen letras raras, impronunciables y extranjeras", "Aunque por definición técnica un binomio y trinomio ya son 'polinomios', en el lenguaje cotidiano y brutal del taller reservamos el título de 'Polinomio' (el Monstruo) exclusivamente para aquellas expresiones colosales que tienen 4 o más términos en cadena. Ejemplo letal: $x^4 - 3x^3 + 2x - 5$", "A los planos que solo tienen letras oscuras y ningún número", "A las ecuaciones rotas que siempre dan como resultado cero absoluto"], correct: 1 },
    { question: "Escaneo Visual Rápido: Observa fríamente esta orden de corte del láser: $\\frac{5xy}{2} + 8z - 3$. ¿Cuántos términos hay realmente en la mesa y cómo se llama la bestia?", options: ["Hay 5 términos y es un Polinomio", "Hay exactamente 3 términos, por lo que es un Trinomio. Míralo con ojos de gerente: El primer bloque compacto es $\\frac{5xy}{2}$, luego hay un grueso muro ($+$), el segundo bloque es el $8z$, luego otro fuerte muro ($-$), y el tercer bloque final es el humilde $3$", "Hay 1 solo término gigante (Monomio)", "Hay 2 términos incompletos (Binomio)"], correct: 1 },
    { question: "Conclusión de Auditoría Corporativa: ¿Por qué dominar la clasificación de los polinomios te hace instantáneamente un mejor gerente de proyectos (ABP)?", options: ["Simplemente para poder aprobar los exámenes escolares memorizando nombres antiguos", "¡Para saber cuánto cobrar exactamente por la complejidad real del trabajo! No puedes ni debes cobrar lo mismo por procesar en la computadora un diseño aburrido y simple (Monomio de una pieza) que por programar toda la noche el láser para un proyecto monstruoso (Polinomio de 5 piezas). Clasificar rápido es cotizar con precisión de francotirador", "Para dibujar mucho más bonito los planos técnicos en el papel milimétrico", "Para ordenar estéticamente los archivos de la fábrica por estricto orden alfabético"], correct: 1 }
];
